# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abefb9f52655ca403682958c4eb615ce89b7a0b069d72d31ac11cbbf78a07b76765a165e7a5fe2950d1832cc4c49d94d44f480d9595a384fc5e3620c291d0e4f

test:
  secret_key_base: c0432fdee37a489c4d9ef97235c8e388c56ca3b676f413bbb2a29f3bb700101ab4c19c73f30ea163f6b9fe984459d6711ab16b45064603ce8f7748391881e6bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
